<a href="https://colab.research.google.com/github/Rahuldeb55/Machine-learning-laboratory/blob/main/lab_05/Logistic_reg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

np.random.seed(42)
X = np.random.rand(100, 2) * 10
y = (X[:, 0] + X[:, 1] > 10).astype(int)

print("Generated X (first 5 rows):\n", X[:5])
print("Generated y (first 5 values):\n", y[:5])

Generated X (first 5 rows):
 [[3.74540119 9.50714306]
 [7.31993942 5.98658484]
 [1.5601864  1.5599452 ]
 [0.58083612 8.66176146]
 [6.01115012 7.08072578]]
Generated y (first 5 values):
 [1 1 0 0 1]


In [2]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"Training data shape: {X_train.shape}")
print(f"Testing data shape: {X_test.shape}")

Training data shape: (70, 2)
Testing data shape: (30, 2)


In [3]:
model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

print("Logistic Regression model trained successfully.")

Logistic Regression model trained successfully.


In [4]:
y_pred = model.predict(X_test)

print("Predictions (first 5 values):\n", y_pred[:5])
print("Actual values (first 5 values):\n", y_test[:5])

Predictions (first 5 values):
 [0 1 1 0 1]
Actual values (first 5 values):
 [0 1 1 0 1]


In [5]:
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"\nModel Accuracy: {accuracy:.2f}")
print("\nClassification Report:\n", report)


Model Accuracy: 0.97

Classification Report:
               precision    recall  f1-score   support

           0       0.94      1.00      0.97        15
           1       1.00      0.93      0.97        15

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

